version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
